<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-8G0J9BJ" failures="1" tests="3" name="Submit order test" time="22.918" errors="0" timestamp="2023-04-15T17:18:29 AWST">
  <testcase classname="TestCases.LoginUser" name="loginInvalidUser" time="0.454">
    <failure type="java.lang.AssertionError" message="expected [Epic sadface: Username and password dos not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]">
      <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password dos not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]
at TestCases.LoginUser.loginInvalidUser(LoginUser.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 37 stack frames]]>
    </failure>
  </testcase> <!-- loginInvalidUser -->
  <testcase classname="TestCases.LoginUser" name="loginValidUser" time="0.462"/>
  <testcase classname="TestCases.ProductPageTest" name="checkOutProduct" time="10.815"/>
</testsuite> <!-- Submit order test -->
