<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-04-15T17:18:06 AWST" name="Suite" finished-at="2023-04-15T17:18:29 AWST" duration-ms="22918">
    <groups>
    </groups>
    <test started-at="2023-04-15T17:18:06 AWST" name="Submit order test" finished-at="2023-04-15T17:18:29 AWST" duration-ms="22918">
      <class name="TestCases.ProductPageTest">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:TestCases.ProductPageTest@3cae7b8b]" started-at="2023-04-15T17:18:16 AWST" name="launchApp" finished-at="2023-04-15T17:18:18 AWST" duration-ms="1846" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="checkOutProduct()[pri:0, instance:TestCases.ProductPageTest@3cae7b8b]" started-at="2023-04-15T17:18:18 AWST" name="checkOutProduct" description="Choose Sauce Labs Jacket" finished-at="2023-04-15T17:18:29 AWST" duration-ms="10815" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkOutProduct -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.ProductPageTest@3cae7b8b]" started-at="2023-04-15T17:18:29 AWST" name="tearDown" finished-at="2023-04-15T17:18:29 AWST" duration-ms="653" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.ProductPageTest -->
      <class name="TestCases.LoginUser">
        <test-method is-config="true" signature="launchApp()[pri:0, instance:TestCases.LoginUser@7186333e]" started-at="2023-04-15T17:18:07 AWST" name="launchApp" finished-at="2023-04-15T17:18:12 AWST" duration-ms="5143" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="loginInvalidUser()[pri:0, instance:TestCases.LoginUser@7186333e]" started-at="2023-04-15T17:18:12 AWST" name="loginInvalidUser" description="Login invalid user" finished-at="2023-04-15T17:18:12 AWST" duration-ms="454" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Epic sadface: Username and password dos not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Epic sadface: Username and password dos not match any user in this service] but found [Epic sadface: Username and password do not match any user in this service]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1577)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at TestCases.LoginUser.loginInvalidUser(LoginUser.java:34)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginInvalidUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.LoginUser@7186333e]" started-at="2023-04-15T17:18:13 AWST" name="tearDown" finished-at="2023-04-15T17:18:13 AWST" duration-ms="690" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApp()[pri:0, instance:TestCases.LoginUser@7186333e]" started-at="2023-04-15T17:18:13 AWST" name="launchApp" finished-at="2023-04-15T17:18:15 AWST" duration-ms="1652" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApp -->
        <test-method signature="loginValidUser()[pri:0, instance:TestCases.LoginUser@7186333e]" started-at="2023-04-15T17:18:15 AWST" name="loginValidUser" description="Login valid user" finished-at="2023-04-15T17:18:15 AWST" duration-ms="462" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginValidUser -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:TestCases.LoginUser@7186333e]" started-at="2023-04-15T17:18:15 AWST" name="tearDown" finished-at="2023-04-15T17:18:16 AWST" duration-ms="726" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestCases.LoginUser -->
    </test> <!-- Submit order test -->
  </suite> <!-- Suite -->
</testng-results>
